version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout

      - run:
          name: build the jekyll site
          command: "curl --location --request POST 'https://api.github.com/repos/sharnam19/continuous-integration-circle/deployments' \
--header 'Accept: application/vnd.github.v3+json' \
--header 'Authorization: Bearer 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' \
--header 'Content-Type: application/json' \
--data-raw '{
    \"ref\":\"1.0.0\",
    \"task\":\"deploy\",
    \"auto_merge\": true,
    \"environment\": \"Prod\",
    \"description\": \"CircleCI Deployment -4th March - Tag \"}'"

      - run:
          name: notify build is finished
          command: echo "The build is finished!"